version: '2'

services:
  lemmy:
    image: {{ lemmy_docker_image }}
    ports:
      - "127.0.0.1:{{ lemmy_port }}:8536"
    restart: always
    environment:
      - RUST_LOG="warn,lemmy_server=info,lemmy_api=info,lemmy_api_common=info,lemmy_api_crud=info,lemmy_apub=info,lemmy_db_queries=info,lemmy_db_schema=info,lemmy_db_views=info,lemmy_db_views_actor=info,lemmy_db_views_moderator=info,lemmy_routes=info,lemmy_utils=info,lemmy_websocket=info"
    volumes:
      - ./lemmy.hjson:/config/config.hjson
    depends_on:
      - postgres
      - pictrs
      - otel

  lemmy-ui:
    image: {{ lemmy_docker_ui_image }}
    ports:
      - "127.0.0.1:{{ lemmy_ui_port }}:1234"
    restart: always
    environment:
      - LEMMY_INTERNAL_HOST=lemmy:8536
      - LEMMY_EXTERNAL_HOST={{ domain }}
      - LEMMY_HTTPS=true
    volumes:
      - ./volumes/lemmy-ui/extra_themes:/app/extra_themes
    depends_on:
      - lemmy

  lemmy-uit:
    image: {{ lemmy_docker_uit_image }}
    ports:
      - "127.0.0.1:{{ lemmy_uit_port }}:1234"
    restart: always
    environment:
      - LEMMY_INTERNAL_HOST=lemmy:8536
      - LEMMY_EXTERNAL_HOST={{ domain2 }}
      - LEMMY_HTTPS=true
    volumes:
      - ./volumes/lemmy-uit/extra_themes:/app/extra_themes
    depends_on:
      - lemmy

  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=lemmy
      - POSTGRES_PASSWORD={{ postgres_password }}
      - POSTGRES_DB=lemmy
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    restart: always

  pictrs:
    image: asonix/pictrs:0.3.1
    user: 991:991
    environment:
      - PICTRS_OPENTELEMETRY_URL=http://otel:4137
    ports:
      - "127.0.0.1:{{ pictrs_port }}:8080"
    volumes:
      - ./volumes/pictrs:/mnt
    restart: always
    mem_limit: 200m
    depends_on:
      - otel

  postfix:
    image: mwader/postfix-relay
    environment:
      - POSTFIX_myhostname={{ domain }}
    restart: "always"

  otel:
    image: otel/opentelemetry-collector:latest
    command: --config otel-local-config.yaml
    ports:
      - "4317:4317"
    volumes:
      - ./otel.yml:/otel-local-config.yaml
    restart: always
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:1
    ports:
      - "14250:14250"
      # To view traces, visit http://localhost:16686
      - "16686:16686"
    restart: always
